// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icqzgoagqosthgipepdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljcXpnb2FncW9zdGhnaXBlcGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODI1NzAsImV4cCI6MjA2NDY1ODU3MH0.nzLqXrmUOmplR71fW-fumg58DiUOs_cKDqmjeuT8Yrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});